// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID        int32              `json:"id"`
	Module    string             `json:"module"`
	Action    string             `json:"action"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Role struct {
	ID          int32              `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Level       pgtype.Int4        `json:"level"`
	IsSystem    pgtype.Bool        `json:"is_system"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	ID           int32              `json:"id"`
	RoleID       int32              `json:"role_id"`
	PermissionID int32              `json:"permission_id"`
	DataScope    pgtype.Text        `json:"data_scope"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            int32              `json:"id"`
	Username      string             `json:"username"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	ExternalLogin pgtype.Bool        `json:"external_login"`
	EmployeeID    pgtype.Int4        `json:"employee_id"`
	RoleID        pgtype.Int4        `json:"role_id"`
	FullName      string             `json:"full_name"`
	Email         pgtype.Text        `json:"email"`
	Phone         pgtype.Text        `json:"phone"`
	Avatar        pgtype.Text        `json:"avatar"`
	Status        pgtype.Text        `json:"status"`
	LastLoginIp   pgtype.Text        `json:"last_login_ip"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
