// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignEmployeeId(ctx context.Context, arg AssignEmployeeIdParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetRoleById(ctx context.Context, id int32) (Role, error)
	GetRolePermissions(ctx context.Context, roleID int32) ([]GetRolePermissionsRow, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPermissions(ctx context.Context, id int32) ([]GetUserPermissionsRow, error)
	RevokeRefreshToken(ctx context.Context, token string) error
	RevokeUserRefreshTokens(ctx context.Context, userID int32) error
	UpdateUserExternalLogin(ctx context.Context, arg UpdateUserExternalLoginParams) error
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
}

var _ Querier = (*Queries)(nil)
