// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: roles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, description, level, is_system, status, created_at, updated_at FROM roles WHERE code = $1 LIMIT 1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleById = `-- name: GetRoleById :one
SELECT id, code, name, description, level, is_system, status, created_at, updated_at FROM roles WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoleById(ctx context.Context, id int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleById, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.module, p.action, p.code, p.name, p.created_at, rp.data_scope
FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

type GetRolePermissionsRow struct {
	ID        int32              `json:"id"`
	Module    string             `json:"module"`
	Action    string             `json:"action"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DataScope pgtype.Text        `json:"data_scope"`
}

func (q *Queries) GetRolePermissions(ctx context.Context, roleID int32) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolePermissionsRow
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Action,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.DataScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT p.code as permission_code, rp.data_scope
FROM users u
JOIN roles r ON u.role_id = r.id
JOIN role_permissions rp ON r.id = rp.role_id
JOIN permissions p ON rp.permission_id = p.id
WHERE u.id = $1
`

type GetUserPermissionsRow struct {
	PermissionCode string      `json:"permission_code"`
	DataScope      pgtype.Text `json:"data_scope"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, id int32) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPermissionsRow
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(&i.PermissionCode, &i.DataScope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
