// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignEmployeeId = `-- name: AssignEmployeeId :exec
UPDATE users
SET employee_id = $2
WHERE id = $1
`

type AssignEmployeeIdParams struct {
	ID         int32       `json:"id"`
	EmployeeID pgtype.Int4 `json:"employee_id"`
}

func (q *Queries) AssignEmployeeId(ctx context.Context, arg AssignEmployeeIdParams) error {
	_, err := q.db.Exec(ctx, assignEmployeeId, arg.ID, arg.EmployeeID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, password_hash, full_name, email, phone, avatar, role_id, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, username, password_hash, external_login, employee_id, role_id, full_name, email, phone, avatar, status, last_login_ip, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	PasswordHash pgtype.Text `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Avatar       pgtype.Text `json:"avatar"`
	RoleID       pgtype.Int4 `json:"role_id"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Avatar,
		arg.RoleID,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.ExternalLogin,
		&i.EmployeeID,
		&i.RoleID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, password_hash, external_login, employee_id, role_id, full_name, email, phone, avatar, status, last_login_ip, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.ExternalLogin,
		&i.EmployeeID,
		&i.RoleID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password_hash, external_login, employee_id, role_id, full_name, email, phone, avatar, status, last_login_ip, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.ExternalLogin,
		&i.EmployeeID,
		&i.RoleID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, external_login, employee_id, role_id, full_name, email, phone, avatar, status, last_login_ip, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.ExternalLogin,
		&i.EmployeeID,
		&i.RoleID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.Status,
		&i.LastLoginIp,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserExternalLogin = `-- name: UpdateUserExternalLogin :exec
UPDATE users
SET external_login = $2
WHERE id = $1
`

type UpdateUserExternalLoginParams struct {
	ID            int32       `json:"id"`
	ExternalLogin pgtype.Bool `json:"external_login"`
}

func (q *Queries) UpdateUserExternalLogin(ctx context.Context, arg UpdateUserExternalLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserExternalLogin, arg.ID, arg.ExternalLogin)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(), last_login_ip = $2
WHERE id = $1
`

type UpdateUserLastLoginParams struct {
	ID          int32       `json:"id"`
	LastLoginIp pgtype.Text `json:"last_login_ip"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID, arg.LastLoginIp)
	return err
}
